# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
    proto:
        desc: Lint proto and regenerate connect-go code for development.
        cmds:
            - task: proto:lint
            - task: proto:gen:go

    proto:authz-link:
      cmds:
        - mkdir -p proto
        - rm -f proto/authz
        - ln -s "$(XDG_CACHE_HOME=/tmp go tool protoc-gen-authz-go --proto-path)/authz" proto/authz

    proto:lint:
        desc: Lint proto.
        deps:
          - proto:authz-link
        cmds:
            - buf lint

    proto:gen:go:
        desc: Regenerate connect-go code from proto.
        deps:
          - proto:authz-link
        cmds:
            - buf generate --template buf.gen.go.yaml
        sources:
            - "proto/**/*.proto"
            - buf.yaml
            - buf.gen.go.yaml
        generates:
            - "gen/**/*"

    proto:gen:es:
        desc: Regenerate connect-es code from proto.
        deps:
          - proto:authz-link
        cmds:
            - buf generate --template buf.gen.es.yaml
        sources:
            - "proto/**/*.proto"
            - buf.yaml
            - buf.gen.es.yaml
            - clients/connect-es/package.json
        generates:
            - "clients/connect-es/gen/**/*"
